name: Auto Merge Weblate PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Vérifier si le PAT_TOKEN est défini
        run: |
          if [[ -z "${{ secrets.PAT_TOKEN }}" ]]; then
            echo "PAT_TOKEN est vide !"
            exit 1
          else
            echo "PAT_TOKEN est bien défini."
          fi

      - name: Vérifier si la PR vient de Weblate
        id: check_pr
        run: |
          AUTHOR="${{ github.event.pull_request.user.login }}"
          TITLE="${{ github.event.pull_request.title }}"
          if [[ ("$AUTHOR" == "fonderie-vtt-weblate" || "$AUTHOR" == "adgranger") && "$TITLE" == "Translations update from Fonderie VTT - Weblate" ]]; then
            echo "MERGE=true" >> $GITHUB_ENV
          else
            echo "MERGE=false" >> $GITHUB_ENV
          fi

      - name: Auto-merge la PR si elle correspond aux critères
        if: env.MERGE == 'true'        
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "rebase"
