name: Auto Merge Weblate PR

on:
  pull_request:
    types: [opened, reopened]
    
permissions:  
  pull-requests: write  
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Check PR author and title
        id: check_pr
        run: |
          if [ "${{ github.event.pull_request.user.login }}" == "fonderie-vtt-weblate" ] && \
             [ "${{ github.event.pull_request.title }}" == "Translations update from Fonderie VTT - Weblate" ]; then
            echo "is_trusted=true" >> $GITHUB_ENV
          else
            echo "is_trusted=false" >> $GITHUB_ENV
          fi

      - name: Merge PR
        if: env.is_trusted == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
